server:
  port: 7801


spring:
    datasource:
        name: test
        url: jdbc:mysql://47.106.149.105:3306/zjb1.0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        maxOpenPreparedStatements: 20
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 30MB
    data:
      mongodb:
        host: 47.106.149.105
        port: 27017
#        uri: mongodb://47.106.149.105:27017
#        username: admin
#        password: 123
        database: zjb
    redis:
        host: 47.106.149.105
        port: 6379
        password: rootredis
        jedis:
          pool:
            max-active: 8
    kafka:
        bootstrap-servers: 47.106.149.105:9092
        zookeeper:
            connect: 47.106.149.105:2181
        consumer:
            group-id: defaultGroup
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
            batch-size: 65536
            buffer-memory: 524288


#        authentication-database: admin
#        uri: mongodb://admin:123@47.106.149.105:27017/zjb

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.renchaigao.zujuba.model

mapper:
  mappers:  com.renchaigao.zujuba.dao.mapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check







